FROM php:8.4-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    unzip \
    libonig-dev \
    libzip-dev \
    libxml2-dev \
    zip

# Install PHP extensions untuk Laravel
RUN docker-php-ext-install pdo pdo_mysql

# Install Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www/app

# Pastikan folder app ada
RUN mkdir -p /var/www/app

# Permission
RUN chown -R www-data:www-data /var/www
